export const Role = {
  ADMIN: 'ADMIN',
  TRANSACTIONS: 'TRANSACTIONS',
  OPERATIONS: 'OPERATIONS',
  MERCHANT_ADMIN: 'MERCHANT_ADMIN',
  MERCHANT: 'MERCHANT',
  SUB_MERCHANT: 'SUB_MERCHANT',
  MERCHANT_OPERATIONS: 'MERCHANT_OPERATIONS',
  VENDOR: 'VENDOR',
  VENDOR_OPERATIONS: 'VENDOR_OPERATIONS',
};

export const Status = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  PENDING: 'PENDING',
  DUPLICATE: 'DUPLICATE',
  DISPUTE: 'DISPUTE',
  BANK_MISMATCH: 'BANK_MISMATCH',
  IMAGE_PENDING: 'IMAGE_PENDING',
  ASSIGNED: 'ASSIGNED',
  INITIATED: 'INITIATED',
  DROPPED: 'DROPPED',
  FAILED: 'FAILED',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED',
};

export const Columns = {
  PAYIN: [
    { label: 'SNO', key: 'sno', type: 'text' as const },
    {
      label: 'UTR',
      key: 'bank_res_details',
      type: 'object',
      objectKey: 'amount' as const,
    },
    { label: 'Requested Amount', key: 'amount', type: 'text' as const },
    { label: 'Status', key: 'status', type: 'status' as const },
    {
      label: 'Merchant',
      key: 'merchant_details',
      type: 'object',
      objectKey: 'merchant_code' as const,
    },
    { label: 'Vendor', key: 'vendor_code', type: 'text' as const },
    {
      label: 'User Submitted UTR',
      key: 'user_submitted_utr',
      type: 'text' as const,
    },
    {
      label: 'UTR',
      key: 'bank_res_details',
      type: 'object',
      objectKey: 'utr' as const,
    },
    { label: 'Image', key: 'user_submitted_image', type: 'text' as const },
    { label: 'Action', key: 'action', type: 'action' as const },
  ],
  USERS: [
    { label: 'Name', key: 'first_name', type: 'text' as const },
    { label: 'User Name', key: 'user_name', type: 'text' as const },
    { label: 'Created At', key: 'created_at', type: 'text' as const },
    { label: 'Created By', key: 'created_by', type: 'text' as const },
    { label: 'Is Enable', key: 'is_enabled', type: 'toggle' as const },
  ],
  MERCHANTS: [
    {
      label: 'Sub Merchants',
      key: 'sub_merchants',
      type: 'expand' as const,
    },
    { label: 'Code', key: 'code', type: 'text' as const },
    { label: 'Balance', key: 'balance', type: 'text' as const },
    { label: 'PayIn Range', key: 'payin_range', type: 'text' as const },
    {
      label: 'PayIn Commission',
      key: 'payin_commission',
      type: 'range' as const,
    },
    { label: 'PayOut Range', key: 'payout_range', type: 'text' as const },
    {
      label: 'PayOut Commission',
      key: 'payout_commission',
      type: 'range' as const,
    },
    { label: 'Test Mode', key: 'test_mode', type: 'toggle' as const },
    { label: 'Allow Intent', key: 'allow_intent', type: 'toggle' as const },
    { label: 'Enabled', key: 'is_enabled', type: 'toggle' as const },
    { label: 'Actions', key: 'actions', type: 'actions' as const },
  ],
  PAYOUT: [
    { label: 'SNO.', key: 'sno', type: 'text' as const },
    { label: 'Amount', key: 'amount', type: 'text' as const },
    { label: 'Status', key: 'status', type: 'status' as const },
    {
      label: 'Merchant',
      key: 'merchant_details',
      type: 'object',
      objectKey: 'merchant_code' as const,
    },
    { label: 'Vendor', key: 'vendor_code', type: 'text' as const },
    {
      label: 'Bank Details',
      key: 'user_bank_details',
      type: 'object',
      objectKey: ['acc_no', 'acc_holder_name', 'ifsc_code', 'bank_name'],
    },
    { label: 'Action', key: 'action', type: 'action' as const },
  ],
};
