export const Role = {
  ADMIN: "ADMIN",
  TRANSACTIONS: "TRANSACTIONS",
  OPERATIONS: "OPERATIONS",
  MERCHANT_ADMIN: "MERCHANT_ADMIN",
  MERCHANT: "MERCHANT",
  SUB_MERCHANT: "SUB_MERCHANT",
  MERCHANT_OPERATIONS: "MERCHANT_OPERATIONS",
  VENDOR: "VENDOR",
  VENDOR_OPERATIONS: "VENDOR_OPERATIONS",
};

export const Status = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  PENDING: "PENDING",
  DUPLICATE: "DUPLICATE",
  DISPUTE: "DISPUTE",
  BANK_MISMATCH: "BANK_MISMATCH",
  IMAGE_PENDING: "IMAGE_PENDING",
  ASSIGNED: "ASSIGNED",
  INITIATED: "INITIATED",
  DROPPED: "DROPPED",
  FAILED: "FAILED",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
};

export const Columns = {
  PAYIN: [
    "SNO",
    "Amount",
    "Requested Amount",
    "Status",
    "Merchant",
    "Vendor",
    "User Submitted UTR",
    "UTR",
    "Image",
    "Action",
  ],
};
