export const Role = {
    ADMIN: 'ADMIN',
    TRANSACTIONS: 'TRANSACTIONS',
    OPERATIONS: 'OPERATIONS',
    MERCHANT_ADMIN: 'MERCHANT_ADMIN',
    MERCHANT: 'MERCHANT',
    SUB_MERCHANT: 'SUB_MERCHANT',
    MERCHANT_OPERATIONS: 'MERCHANT_OPERATIONS',
    VENDOR: 'VENDOR',
    VENDOR_OPERATIONS: 'VENDOR_OPERATIONS',
}